module.exports = [
  './gulp/tasks/clean.js',
  './gulp/tasks/images.sprite.js',
  './gulp/tasks/svg.sprite.js',
  './gulp/tasks/pug.js',
  './gulp/tasks/css.vendor.js',
  './gulp/tasks/sass.js',
  './gulp/tasks/sass.lint.js',
  './gulp/tasks/js.vendor.js',
  './gulp/tasks/js.app.js',
  './gulp/tasks/js.app-minify.js',
  './gulp/tasks/js.lint.js',
  './gulp/tasks/fonts.js',
  './gulp/tasks/images.js',
  './gulp/tasks/images.minify.js',
  './gulp/tasks/watch.js',
  './gulp/tasks/serve.js',
];
